adjust_search_result_header_widths = ->
  row = $('table#search_results_table').find('tr').first()
  track = row.children('.track').width()
  title = row.children('.title').width()
  artist = row.children('.artist').width()
  album = row.children('.album').width()
  time = row.children('.time').width()
  file = row.children('.file').width()

  $("table#search_results_table_header .track").width(track)
  $("table#search_results_table_header .title").width(title)
  $("table#search_results_table_header .artist").width(artist)
  $("table#search_results_table_header .album").width(album)
  $("table#search_results_table_header .time").width(time)
  $("table#search_results_table_header .file").width(file)

adjust_search_result_widths = ->
  row = $('table#search_results_table_header').find('tr').first()
  track = $(row).children('.track').width()
  title = $(row).children('.title').width()
  artist = $(row).children('.artist').width()
  album = $(row).children('.album').width()
  time = $(row).children('.time').width()
  file = $(row).children('.file').width()
  rows = $("table#search_results_table").children('tr')
  for row in rows
    $(row).children('.track').width(track)
    $(row).children('.title').width(title)
    $(row).children('.artist').width(artist)
    $(row).children('.album').width(album)
    $(row).children('.time').width(time)
    $(row).children('.file').width(file)